dictionaries = ["en_us", "ru"]
ignore_patterns = [
    '[ა-ჰ]',                   # Georgian characters
    '^[A-Z]{2,}$',             # All caps words like "HTML", "CSS"
    'https?://[^\s]+'          # URLs
]
